version: '3'

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3500:3000"
    volumes:
      - ./server:/app/
      - /app/node_modules
    networks:
      - nodenet
      
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    volumes:
      - ./client:/app/
      - /app/node_modules
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge